blank_issues_enabled: false
contact_links:
  - name: General Question
    url: https://github.com/Loues000/usagebar/issues
    about: Use Issues for questions and discussion until Discussions are enabled here
